linters:
  enable:
    - golint
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - goimports
    - scopelint
    - gofmt
    - unused
    - varcheck
    - typecheck
run:
  skip-dirs:
    - vpc/service/db/migrations
    - aws
    - vpc/bpf/filter
    - vpc/bpf2
    - vpc/limitsold
