steps:
  - command: ./.buildkite/build.sh
    artifact_paths: "src/github.com/Netflix/titus-executor/*.log;src/github.com/Netflix/titus-executor/build/distributions/*.deb;src/github.com/Netflix/titus-executor/build/distributions/*.tar;src/github.com/Netflix/titus-executor/build/distributions/*.tar.gz;src/github.com/Netflix/titus-executor/*.out"
  - wait
  - trigger: titus-upload-debs
    async: false
    branches: "master"
    build:
      env:
        CALLER_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        CALLER_JOB_ID: "${BUILDKITE_JOB_ID}"
        CALLER_UPLOAD_DEB: "src/github.com/Netflix/titus-executor/build/distributions/titus-executor_latest.deb"
        CALLER_PACKAGE_NAME: "titus-executor"
        BUILDKITE_CLEAN_CHECKOUT: "true"